export enum CART_REDUCER_TYPES {
  SET_CART_ITEMS = "cart/SET_CART_ITEMS",
  SET_CART_OPEN = "cart/SET_CART_OPEN",
  // SET_TOTAL_QUANTITY: "cart/SET_TOTAL_QUANTITY",
  // SET_CART_TOTAL: "cart/SET_CART_TOTAL",
}
